apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
# namespace: Anamespace
patchesStrategicMerge:
- set_replica.yaml
- set_environment.yaml
- resource-requirement.yaml
resources:
- service.yaml
# - ingress-controller-api.yaml
- SecretProviderClass.yaml
